name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: [bug, triage]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of re-frame-10x are you using?
      options:
        - 1.1.8 (Default)
        - 1.1.7
        - 1.1.6
        - 1.1.5
        - 1.1.4
        - 1.1.3
        - 1.1.2
        - 1.1.1
        - 1.1.0
        - 1.0.2
        - 1.0.1
        - 1.0.0
        - 0.7.0
        - 0.6.7
        - 0.6.6
        - 0.6.5
        - 0.6.4
        - 0.6.3
        - 0.6.2
        - 0.6.1
        - 0.6.0
        - 0.5.2
        - 0.5.1
        - 0.5.0
        - 0.4.7
        - 0.4.6
        - 0.4.7
        - 0.4.6
        - 0.4.5
        - 0.4.4
        - 0.4.3
        - 0.4.2
        - 0.4.1
        - 0.4.0
        - 0.3.7
        - 0.3.6
        - 0.3.5
        - 0.3.4
        - 0.3.3
        - 0.3.2
        - 0.3.1-react16
        - 0.3.1
        - 0.3.0-react16
        - 0.3.0
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant console output
      description: Please copy and paste any relevant console output. This will be automatically formatted into code, so no need for backticks.
      render: shell
