name: ci
on:
  push:
    paths-ignore:
      - "docs/**"
      - ".gitignore"
      - "CHANGELOG.md"
      - "DEVELOPERS.md"
      - "LICENSE"
      - "README.md"

jobs:
  test:
    name: Test
    runs-on: ubuntu-18.04
    container:
      # Ref: https://github.community/t5/GitHub-Actions/docker-pull-from-public-GitHub-Package-Registry-fail-with-quot/m-p/32782
      image: superstructor/clojure:openjdk-11-lein-2.9.1-node-browser
    steps:
      - uses: actions/checkout@v1
      - run: lein test
      - name: Install re-frame-10x for Sample Projects
        run: lein install
      - name: Compile Sample Project for Development
        run: lein with-profile dev do clean, compile
        working-directory: "examples/todomvc"
      - name: Compiler Sample Project for Production
        run: lein with-profile prod do clean, compile
        working-directory: "examples/todomvc"
